/* NEXUS PERSONA V10: respostas locais verificáveis e memória SOMENTE da sessão.
  Não são respostas generativas: só responde tópicos cobertos pela base resumida.
  Informe insuficiência para perguntas fora do acervo. */
(function(global){
"use strict";
const normalized=s=>String(s||"").toLocaleLowerCase("pt-BR").normalize("NFD")
  .replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9 ]/g," ").replace(/\s+/g," ").trim();
const STOP=new Set("a o os as de da do das dos e ou para por que qual quais como pode devo um uma no na nos nas isso isto essa este mais fale explique sobre voce me eu quero saber funciona funciona".split(" "));
const topics=[
{ id:"brasil", title:"BRASIL 2075", triggers:["brasil 2075","objetivo do programa","o que e o projeto","proposta brasil","para que serve brasil"], terms:["brasil","2075","programa","futuro","civilizacao"], answer:"BRASIL 2075 é uma proposta de investigação universitária sobre colaboração entre inteligência humana e inteligência artificial. O ano de 2075 é um horizonte de pesquisa e reflexão, não uma previsão científica nem uma promessa de resultados.", expand:"Seu princípio orientador é utilizar tecnologias para ampliar o conhecimento e as possibilidades humanas, preservando autonomia, avaliação científica e responsabilidade institucional." },
{ id:"papel", title:"Papel das universidades", triggers:["qual papel das universidades","universidade pode participar","participacao universitaria","parceria universitaria"], terms:["universidade","instituicao","participar","parceria","reitoria"], answer:"As universidades podem definir problemas de pesquisa, autorizar atividades-piloto, estabelecer critérios de avaliação e decidir se os resultados justificam a continuidade. A participação é uma decisão de cada instituição.", expand:"A proposta recomenda equipes interdisciplinares, acompanhamento acadêmico e registro claro de objetivos, limites e resultados." },
{ id:"piloto", title:"Piloto de 90 dias", triggers:["projeto piloto","piloto universitario","noventa dias","90 dias"], terms:["piloto","90","dias","implementacao","cronograma"], answer:"O piloto universitário proposto dura 90 dias: definição dos objetivos e recursos; preparação metodológica; atividades autorizadas; e avaliação com relatório final. A execução depende de autorização e recursos da instituição.", expand:"A proposta divide os períodos em dias 1–15, 16–30, 31–60 e 61–90. A última etapa deve documentar o que funcionou, o que falhou e o que ainda requer estudo." },
{ id:"nexus", title:"Ecossistema NEXUS", triggers:["nucleos do nexus","areas do nexus","o que e nexus","sigla nexus","quais sao os nucleos"], terms:["nexus","nucleos","ecosistema","frentes"], answer:"O ecossistema NEXUS apresenta frentes de investigação em educação, saúde, cognição, memória, infraestrutura e mediação linguística. Elas são propostas de trabalho com necessidades próprias de pesquisa e validação.", expand:"Os núcleos listados nesta apresentação são EDU, MED, ODONTO, MIND, MEMORY, CORE e UNIVERSAL. Nem todos têm a mesma maturidade tecnológica." },
{ id:"edu", title:"NEXUS EDU", triggers:["nexus edu","nexus educacao","aprendizagem por desafios"], terms:["edu","educacao","ensino","aluno","professor","aprender","aprendizagem"], answer:"NEXUS EDU propõe investigar recursos inteligentes de apoio à aprendizagem e atividades por desafios em ambientes universitários. A tecnologia deve apoiar o professor e a autonomia do estudante, não substituir o trabalho pedagógico.", expand:"Uma aplicação experimental precisa definir critérios pedagógicos, acessibilidade, acompanhamento humano e maneiras objetivas de avaliar aprendizagem." },
{ id:"med", title:"NEXUS MED", triggers:["nexus med","nexus medicina","pacientes virtuais"], terms:["med","medicina","medica","paciente","saude"], answer:"NEXUS MED propõe investigar pacientes virtuais e ferramentas de apoio à formação médica. Essa frente é educacional e experimental: não substitui diagnóstico, atendimento nem supervisão de profissionais.", expand:"Qualquer aplicação em saúde exigiria validação específica, medidas de segurança, consentimento e governança institucional adequados." },
{ id:"odonto", title:"NEXUS ODONTO", triggers:["nexus odonto","odontologia","formacao odontologica"], terms:["odonto","odontologia","dentista","anatomia"], answer:"NEXUS ODONTO propõe estudar representações anatômicas e recursos de aprendizagem na formação odontológica, sob supervisão de docentes. Não é um produto clínico validado.", expand:"O objetivo do piloto é investigar utilidade didática e limitações das ferramentas antes de considerar outras aplicações." },
{ id:"mind", title:"NEXUS MIND", triggers:["nexus mind","cognicao humana","interacao humano maquina"], terms:["mind","cognicao","mente","interacao","neuro"], answer:"NEXUS MIND é a frente prospectiva dedicada a estudar cognição e interação entre pessoas e sistemas inteligentes. Hipóteses de integração cognitiva profunda devem ser tratadas como pesquisa futura, não como capacidades já demonstradas.", expand:"A investigação exige separar resultados observáveis, protótipos experimentais e hipóteses de longo prazo." },
{ id:"memory", title:"NEXUS MEMORY", triggers:["nexus memory","preservar memoria","acervos digitais"], terms:["memory","memoria","acervo","preservacao","arquivos"], answer:"NEXUS MEMORY trata da preservação de acervos e do acesso ao conhecimento, com atenção à autoria, às fontes, ao contexto e à responsabilidade pelo tratamento das informações.", expand:"Uma instituição participante pode estudar organização, busca, acessibilidade e mecanismos de verificação de materiais autorizados." },
{ id:"core", title:"NEXUS CORE", triggers:["nexus core","infraestrutura segura","arquitetura de sistemas"], terms:["core","infraestrutura","seguranca","sistemas","arquitetura"], answer:"NEXUS CORE reúne a discussão sobre infraestrutura tecnológica, segurança e supervisão necessárias às aplicações experimentais. A prioridade é começar por recursos compatíveis com os ambientes universitários existentes.", expand:"Antes de expandir, a instituição deve avaliar custo, manutenção, segurança, acessibilidade, governança e utilidade." },
{ id:"universal", title:"NEXUS UNIVERSAL", triggers:["nexus universal","mediacao linguistica","traducao de idiomas"], terms:["universal","traducao","idiomas","linguas","internacional"], answer:"NEXUS UNIVERSAL é a frente proposta para mediação linguística e ampliação do acesso ao conhecimento. As traduções devem ser revisadas quando precisão conceitual, técnica ou jurídica for necessária.", expand:"A seleção de idioma de uma voz no navegador não traduz o texto automaticamente. Tradução integral exige conteúdo ou serviço específico." },
{ id:"niveis", title:"Níveis de integração", triggers:["tres niveis de integracao","niveis de integracao","neurotecnologia","integracao profunda"], terms:["integracao","niveis","assistiva","neurotecnologia"], answer:"O projeto diferencia três níveis: integração funcional com ferramentas digitais; integração assistiva ou neurotecnológica sujeita a estudos; e integração cognitiva profunda como hipótese de longo prazo ainda não demonstrada.", expand:"Distinguir esses níveis evita apresentar hipóteses futuras como tecnologias disponíveis hoje." },
{ id:"etica", title:"Ética e privacidade", triggers:["etica do projeto","privacidade dos dados","dados pessoais","consentimento"], terms:["etica","privacidade","consentimento","dados","seguranca","limites"], answer:"A investigação deve proteger privacidade, consentimento, autoria, acessibilidade e supervisão humana. Dados pessoais e decisões de alto impacto exigem avaliação adicional por responsáveis competentes.", expand:"O avatar informa quando é uma representação digital e deve declarar suas limitações. Gravação de voz, criação de modelos faciais e armazenamento de perguntas requerem autorização e regras transparentes." },
{ id:"autonomia", title:"Autonomia humana", triggers:["ia substitui","inteligencia artificial substitui professores","responsabilidade humana","quem decide"], terms:["autonomia","responsabilidade","substituir","decisao","humanidade","controle"], answer:"O propósito declarado não é substituir decisões humanas. A inteligência artificial deve ser instrumento de apoio, enquanto docentes, pesquisadores e instituições mantêm responsabilidade pelo uso e pela avaliação dos resultados.", expand:"Informação não substitui compreensão; conhecimento deve ampliar a capacidade de escolher, não entregar decisões prontas." },
{ id:"infra", title:"Ambiente universitário", triggers:["sala universitaria","precisa de sala futurista","equipamentos necessarios","infraestrutura inicial"], terms:["sala","computadores","equipamentos","infraestrutura","campus"], answer:"A proposta prevê começar em salas universitárias convencionais, com computadores, telas e recursos de áudio e acessibilidade. Infraestruturas mais sofisticadas dependem do objetivo do piloto e dos recursos disponíveis.", expand:"Uma apresentação pode usar o NEXUS PERSONA em um navegador e um projetor; experiências tridimensionais exigem testes específicos de desempenho." },
{ id:"avatar", title:"O que é NEXUS PERSONA?", triggers:["quem e voce","quem e o avatar","nexus persona","voce e professor dal piero"], terms:["avatar","persona","quem","voce","assistente"], answer:"Sou o NEXUS PERSONA, uma representação digital desenvolvida para apresentar o projeto BRASIL 2075 e responder a perguntas sobre seu conteúdo autorizado. Não sou o Professor Dal Piero falando ao vivo.", expand:"O vídeo de apresentação preserva uma gravação original. Respostas novas exigem um sistema de perguntas e voz; animação facial precisa depende de um modelo tridimensional aprovado." },
{ id:"voz", title:"Voz e movimento", triggers:["sua voz e original","voz do autor","movimento da boca","sincronizacao labial"], terms:["voz","fala","boca","expressao","movimentos","filme"], answer:"Na apresentação, o NEXUS reproduz o Filme 2 com imagem e áudio originais. Para respostas inéditas, a voz oficial depende de um serviço autorizado configurado no servidor. Sem isso, posso mostrar a resposta em texto ou usar, mediante opção, uma voz provisória identificada.", expand:"Movimentos discretos de enquadramento não equivalem a sincronização labial. Uma malha tridimensional aprovada é necessária para representar novas falas com expressões controladas." },
{ id:"documentos", title:"Informações e fontes", triggers:["quais sao suas fontes","de onde vem a informacao","comprovar informacao"], terms:["fonte","referencia","documentos","verificar","comprovacao"], answer:"Minhas respostas locais vêm de uma base institucional resumida do projeto BRASIL 2075. Esta versão não consulta automaticamente todo o dossiê, nem substitui a leitura dos documentos originais.", expand:"Para afirmações não cobertas pela base, solicite à equipe responsável a documentação pertinente em vez de tratar uma resposta sintética como evidência." },
{ id:"resultados", title:"Resultados e maturidade", triggers:["ja funciona","resultados comprovados","projeto implementado","esta pronto"], terms:["resultado","comprovado","implantado","validado","pronto"], answer:"A apresentação reúne propostas, componentes experimentais e horizontes de pesquisa. A existência de um protótipo não comprova resultados pedagógicos, clínicos ou científicos. Cada aplicação precisa de avaliação própria.", expand:"Projetos-piloto servem justamente para observar viabilidade, limites, resultados e próximos ajustes." },
{ id:"contato", title:"Próximos passos", triggers:["como entrar em contato","onde conhecer o projeto","como participar","o que fazer agora"], terms:["contato","conhecer","proposta","participar","reuniao"], answer:"Instituições interessadas podem consultar os materiais institucionais do projeto, definir um problema concreto de pesquisa e avaliar a conveniência de um piloto. O desenvolvimento depende de diálogo e aprovação institucional.", expand:"A primeira reunião pode estabelecer escopo, equipe, acesso aos materiais, critérios de sucesso e responsabilidades." }
];
function tokens(s){return normalized(s).split(" ").filter(w=>w.length>=3&&!STOP.has(w))}
function resolve(question,context){
 const q=normalized(question),words=tokens(question);
 if(!q)return {found:false,answer:"Por favor, formule uma pergunta.",id:null};
 if(/^(mais|detalhes|explique melhor|pode detalhar|e sobre isso|como assim|continue)( |$)/.test(q)&&context){
   const topic=topics.find(t=>t.id===context);
   if(topic)return {found:true,id:topic.id,answer:topic.expand,source:"Base institucional resumida — "+topic.title};
 }
 let best=null,bestScore=0,second=0;
 for(const topic of topics){
   let score=0;
   for(const tr of topic.triggers){
     const p=normalized(tr);
     if(q.includes(p))score+=10+p.split(" ").length*2;
   }
   const kw=topic.terms.map(normalized);
   const overlaps=words.filter(w=>kw.some(k=>k===w||(w.length>=5&&k.startsWith(w)))).length;
   score+=overlaps*2;
   if(score>bestScore){second=bestScore;bestScore=score;best=topic}
   else second=Math.max(second,score);
 }
 // Don't make a weak guess from just "universidade"/"programa"/etc.
 const generic=new Set(["programa","projeto","universidade","nexus","sistema","futuro","conhecer","proposta"]);
 if(bestScore<4||(bestScore<10&&words.length>1&&words.every(w=>generic.has(w)))){
   return {found:false,id:null,answer:"Não encontrei uma resposta segura na base resumida do BRASIL 2075 para essa pergunta. Posso explicar os tópicos disponíveis ou, quando o servidor autorizado estiver conectado, consultar a IA e apresentar uma resposta fundamentada.",source:"Base institucional insuficiente"};
 }
 return {found:true,id:best.id,answer:best.answer,source:"Base institucional resumida — "+best.title};
}
global.NEXUS_KB=Object.freeze({resolve,topics:topics.map(t=>Object.freeze({id:t.id,title:t.title}))});
})(typeof window!=="undefined"?window:globalThis);
